version: "3.9"

services:
  algafood-db:
    image: mysql:8
    container_name: algafood-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    restart: always
    networks:
      - algafood-network

  algafood-api:
    build: .
    container_name: algafood-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=algafood-db
    depends_on:
      - algafood-db
    restart: always
    networks:
      - algafood-network
    
networks:
  algafood-network:
    driver: bridge