version: "3.9"

services:
  algafood-db:
    image: mysql:8
    container_name: algafood-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    networks:
      - algafood-network

  algafood-api:
    build: .
    command: ["/wait-for-it.sh", "algafood-db:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      - DB_HOST=algafood-db
    depends_on:
      - algafood-db
    networks:
      - algafood-network
    
networks:
  algafood-network:
    driver: bridge