version: "3.9"

services:
  algafood-db:
    image: mysql:8
    container_name: algafood-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    networks:
      - algafood-network
      
  algafood-redis:
    image: redis:7.0-alpine
    container_name: algafood-redis
    networks:
      - algafood-network

  algafood-api:
    build: .
    command: ["/wait-for-it.sh", "algafood-db:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      - DB_HOST=algafood-db
      - SPRING_SESSION_STORE_TYPE=redis
      - SPRING_REDIS_HOST=algafood-redis
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - algafood-db
    networks:
      - algafood-network
      
  algafood-proxy:
    build: ./nginx
    container_name: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api
    
networks:
  algafood-network:
    driver: bridge